### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by friishon** [Xearoxde/Maven#2]
i have this error with the plugin xdaily
![xdaily](https://cloud.githubusercontent.com/assets/19889173/17835020/aa71e294-6759-11e6-8638-b00baebb7b0f.PNG)

**Comment by Xearoxde** [comment]
Which color codes do you use? Because you should use $ instead of & as alternate color code. What do you write in the language file?

**Comment by friishon** [comment]
nothing, only i put it on my server and start
i'm login and write /daily admin
and i have this error
